
[shortcuts] # ~/.config/akeyshually/shortcuts.toml
"super+k" = "edit_config"

#-[LAUNCHERS]--------------------------------

"super" = "rofi"
"super+b" = "browser"
"super+shift+b" = "browser2"
"super+return" = "kitty"
"super+f" = "dolphin"
"super+x" = "xkill"
"super+e" = "email"
#"ctrl+alt+t" = "kitty"
"super+v" = "copyq toggle"
"super+w" = "whatsapp"
"shift+super+n" = "notetaker"

#-[UTILS]------------------------------------

"print" = "prtscr"
"super+p" = "prtscr"
"shift+print" = "/home/user/Workspace/tools/bin/screenshot-save"
"ctrl+print" = "bash -c \"xdg-open ~/Media/Pictures/temp.png\""
"f9" = "yap"
"ctrl+mute" = "mute_mic"


"ctrl+shift+alt+h"="xdotool mousemove_relative 2 0"



[commands]#----------------------------------

edit_config = "kitty micro ~/.config/akeyshually/shortcuts.toml"

browser = "brave-browser --user-data-dir=/home/user/.config/BraveSoftware/1"
browser2 = "brave-browser --user-data-dir=/home/user/.config/BraveSoftware/2"
dmenu = "bash -c \"compgen -c | dmenu | sh\""
rofi = "~/.config/rofi/scripts/launcher_t7"
email = "flatpak run org.mozilla.Thunderbird"
mute_mic = "pactl set-source-mute @DEFAULT_SOURCE@ toggle"
whatsapp = "flatpak run com.rtosta.zapzap"
notetaker = "bash -c \"source ~/.bashrc && /home/user/.config/bash/bin/notetaker/notetaker\""
prtscr = "/home/user/Workspace/tools/bin/screenshot-save --temp"